# Generated by Django 3.2.15 on 2023-01-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20230112_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='card_number'),
        ),
    ]
