# Generated by Django 3.2.15 on 2023-01-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20230114_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[(2, 'Англійська'), (1, 'Українська')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[(2, 'Жінка'), (1, 'Чоловік')], max_length=50, null=True),
        ),
    ]
