# Generated by Django 3.2.15 on 2023-01-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20230121_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('1', 'Українська'), (None, ''), ('2', 'Англійська')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Жінка'), (None, ''), ('1', 'Чоловік')], max_length=50, null=True),
        ),
    ]
