# Generated by Django 3.2.15 on 2023-01-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('2', 'Англійська'), ('1', 'Українська'), (None, '')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[(None, ''), ('1', 'Чоловік'), ('2', 'Жінка')], max_length=50, null=True),
        ),
    ]
