# Generated by Django 3.2.15 on 2023-01-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('2', 'Англійська'), (None, ''), ('1', 'Українська')], max_length=50, null=True),
        ),
    ]
