# Generated by Django 3.2.15 on 2023-01-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20230127_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[(None, ''), ('2', 'Англійська'), ('1', 'Українська')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Жінка'), (None, ''), ('1', 'Чоловік')], max_length=50, null=True),
        ),
    ]
