# Generated by Django 3.2.15 on 2023-02-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20230127_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('2', 'Англійська'), ('1', 'Українська'), (None, '')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Чоловік'), ('2', 'Жінка'), (None, '')], max_length=50, null=True),
        ),
    ]
