# Generated by Django 3.2.15 on 2023-02-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20230205_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[(None, ''), ('1', 'Чоловік'), ('2', 'Жінка')], max_length=50, null=True),
        ),
    ]
