# Generated by Django 3.2.15 on 2023-02-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Жінка'), ('1', 'Чоловік'), (None, '')], max_length=50, null=True),
        ),
    ]
