# Generated by Django 3.2.15 on 2023-02-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_auto_20230211_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('1', 'Українська'), ('2', 'Англійська'), (None, '')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', 'Жінка'), (None, ''), ('1', 'Чоловік')], max_length=50, null=True),
        ),
    ]
