# Generated by Django 3.2.15 on 2023-01-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0004_alter_speedcarousel_speed_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('6', '10c'), ('3', '7c'), ('2', '6c'), ('1', '5c'), ('4', '8c'), ('5', '9c')], max_length=50, null=True),
        ),
    ]
