# Generated by Django 3.2.15 on 2023-01-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0005_alter_speedcarousel_speed_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='description',
            new_name='description_uk',
        ),
        migrations.AddField(
            model_name='hall',
            name='description_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('4', '8c'), ('2', '6c'), ('5', '9c'), ('1', '5c'), ('3', '7c'), ('6', '10c')], max_length=50, null=True),
        ),
    ]
