# Generated by Django 3.2.15 on 2023-01-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0006_auto_20230108_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date_create',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('2', '6c'), ('4', '8c'), ('6', '10c'), ('1', '5c'), ('3', '7c'), ('5', '9c')], max_length=50, null=True),
        ),
    ]
