# Generated by Django 3.2.15 on 2023-01-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0007_auto_20230109_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsanddiscount',
            name='date_created_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsanddiscount',
            name='date_premiere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('3', '7c'), ('4', '8c'), ('1', '5c'), ('6', '10c'), ('2', '6c'), ('5', '9c')], max_length=50, null=True),
        ),
    ]
