# Generated by Django 3.2.15 on 2023-01-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0008_auto_20230109_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date_create',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[(1, '5c'), (4, '8c'), (5, '9c'), (3, '7c'), (6, '10c'), (2, '6c')], max_length=50, null=True),
        ),
    ]
