# Generated by Django 3.2.15 on 2023-01-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0024_alter_speedcarousel_speed_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[(1000, '10c'), (None, ''), (300, '3c'), (500, '5c'), (700, '7c')], max_length=50, null=True),
        ),
    ]
