# Generated by Django 3.2.15 on 2023-01-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0028_alter_speedcarousel_speed_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='type',
            field=models.CharField(choices=[('10', 'Фон-картинка'), ('1000', 'Звичаний фон')], max_length=50),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('300', '3c'), ('1000', '10c'), ('500', '5c'), ('700', '7c'), (None, '')], max_length=50, null=True),
        ),
    ]
