# Generated by Django 3.2.15 on 2023-01-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0029_auto_20230121_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('700', '7c'), ('500', '5c'), ('1000', '10c'), (None, ''), ('300', '3c')], max_length=50, null=True),
        ),
    ]
