# Generated by Django 3.2.15 on 2023-01-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0030_auto_20230121_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[(None, ''), ('3000', '3c'), ('7000', '7c'), ('5000', '5c'), ('10000', '10c')], max_length=50, null=True),
        ),
    ]
