# Generated by Django 3.2.15 on 2023-01-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0033_auto_20230125_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[(None, ''), ('10000', '10c'), ('3000', '3c'), ('5000', '5c'), ('7000', '7c')], max_length=50, null=True),
        ),
    ]
