# Generated by Django 3.2.15 on 2023-01-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0034_alter_speedcarousel_speed_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='back_type_img',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='backgroundbanner',
            name='back_type_pick',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('5000', '5c'), (None, ''), ('7000', '7c'), ('10000', '10c'), ('3000', '3c')], max_length=50, null=True),
        ),
    ]
