# Generated by Django 3.2.15 on 2023-01-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0035_auto_20230125_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='back_type_img',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('10000', '10c'), (None, ''), ('3000', '3c'), ('7000', '7c'), ('5000', '5c')], max_length=50, null=True),
        ),
    ]
