# Generated by Django 3.2.15 on 2023-01-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0037_auto_20230125_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='back_type_img',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('7000', '7c'), ('5000', '5c'), ('3000', '3c'), ('10000', '10c'), (None, '')], max_length=50, null=True),
        ),
    ]
