# Generated by Django 3.2.15 on 2023-01-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0038_auto_20230125_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='back_type_img',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='backgroundbanner',
            name='back_type_pick',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('3000', '3c'), ('10000', '10c'), (None, ''), ('5000', '5c'), ('7000', '7c')], max_length=50, null=True),
        ),
    ]
