# Generated by Django 3.2.15 on 2023-01-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0039_auto_20230125_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='back_type_img',
            field=models.BooleanField(default=True, verbose_name='back_check'),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('7000', '7c'), ('10000', '10c'), ('5000', '5c'), (None, ''), ('3000', '3c')], max_length=50, null=True),
        ),
    ]
