# Generated by Django 3.2.15 on 2023-01-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0041_auto_20230125_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='template',
            field=models.FileField(upload_to='file/mailing/'),
        ),
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('5000', '5c'), ('7000', '7c'), ('3000', '3c'), (None, ''), ('10000', '10c')], max_length=50, null=True),
        ),
    ]
