# Generated by Django 3.2.15 on 2023-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0044_auto_20230205_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('5000', '5c'), ('7000', '7c'), ('3000', '3c'), (None, ''), ('10000', '10c')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
