# Generated by Django 3.2.15 on 2023-02-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0045_auto_20230205_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('5000', '5c'), ('7000', '7c'), ('10000', '10c'), ('3000', '3c'), (None, '')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(),
        ),
    ]
