# Generated by Django 3.2.15 on 2023-02-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0046_auto_20230205_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('7000', '7c'), ('10000', '10c'), ('3000', '3c'), ('5000', '5c'), (None, '')], max_length=50, null=True),
        ),
    ]
