# Generated by Django 3.2.15 on 2023-02-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0048_alter_speedcarousel_speed_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedcarousel',
            name='speed_carousel',
            field=models.CharField(blank=True, choices=[('5000', '5c'), ('7000', '7c'), ('3000', '3c'), (None, ''), ('10000', '10c')], max_length=50, null=True),
        ),
    ]
